version: "3.7"

services:
  customer-service:
    image: ghcr.io/thangchung/resilientwithpolly/customer-service:${IMAGE_TAG:-latest}
    build:
      context: ./ProCodeGuide.Polly.Customer
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    restart: always
    networks:
      - resiliency-network

  order-service:
    image: ghcr.io/thangchung/resilientwithpolly/order-service:${IMAGE_TAG:-latest}
    build:
      context: ./ProCodeGuide.Polly.Order
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CustomerUrl=http://customer-service
    ports:
      - "5002:80"
    depends_on:
      - customer-service
    restart: always
    networks:
      - resiliency-network

networks:
  resiliency-network: